-- GENERATED by database/scripts/dump_schema.sh. Do not edit; change schema via migrations.
--
-- PostgreSQL database dump
--



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bq_access_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bq_access_requests (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    scope_type text NOT NULL,
    dataset_id text,
    table_id text,
    justification text,
    duration_hours integer,
    status text DEFAULT 'pending'::text NOT NULL,
    expires_at timestamp with time zone,
    reviewed_by uuid,
    reviewed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT bq_access_requests_duration_hours_check CHECK ((duration_hours > 0)),
    CONSTRAINT bq_access_requests_scope_type_check CHECK ((scope_type = ANY (ARRAY['dataset'::text, 'table'::text]))),
    CONSTRAINT bq_access_requests_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])))
);


--
-- Name: bq_datasets_cache; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bq_datasets_cache (
    id text NOT NULL,
    description text,
    location text,
    table_count integer,
    synced_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: bq_tables_cache; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bq_tables_cache (
    dataset_id text NOT NULL,
    id text NOT NULL,
    description text,
    num_rows bigint,
    num_bytes bigint,
    created_bq timestamp with time zone,
    modified_bq timestamp with time zone,
    synced_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: db_access_grants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.db_access_grants (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    scope_type text NOT NULL,
    database_id uuid,
    table_id uuid,
    source_request_id uuid,
    granted_by uuid NOT NULL,
    granted_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone,
    revoked_at timestamp with time zone,
    revoked_by uuid,
    CONSTRAINT db_access_grants_check CHECK ((((scope_type = 'database'::text) AND (database_id IS NOT NULL)) OR ((scope_type = 'table'::text) AND (table_id IS NOT NULL)))),
    CONSTRAINT db_access_grants_scope_type_check CHECK ((scope_type = ANY (ARRAY['database'::text, 'table'::text])))
);


--
-- Name: db_access_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.db_access_requests (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    scope_type text NOT NULL,
    database_id uuid,
    table_id uuid,
    justification text,
    duration_hours integer,
    status text DEFAULT 'pending'::text NOT NULL,
    reviewed_by uuid,
    reviewed_at timestamp with time zone,
    review_note text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT db_access_requests_duration_hours_check CHECK ((duration_hours > 0)),
    CONSTRAINT db_access_requests_scope_type_check CHECK ((scope_type = ANY (ARRAY['database'::text, 'table'::text]))),
    CONSTRAINT db_access_requests_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])))
);


--
-- Name: password_reset_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_requests (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    resolved_by uuid,
    resolved_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT password_reset_requests_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'resolved'::text, 'cancelled'::text])))
);


--
-- Name: pg_databases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pg_databases (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    description text,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT pg_databases_name_check CHECK ((name ~ '^[A-Za-z_][A-Za-z0-9_]{0,62}$'::text))
);


--
-- Name: pg_tables_catalog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pg_tables_catalog (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    database_id uuid NOT NULL,
    table_name text NOT NULL,
    description text,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT pg_tables_catalog_table_name_check CHECK ((table_name ~ '^[A-Za-z_][A-Za-z0-9_]{0,62}$'::text))
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version integer NOT NULL,
    name text NOT NULL,
    checksum text NOT NULL,
    applied_at timestamp with time zone DEFAULT now() NOT NULL,
    execution_ms integer NOT NULL
);


--
-- Name: upload_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.upload_requests (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    file_id uuid NOT NULL,
    file_version integer NOT NULL,
    target_type text NOT NULL,
    target_database text,
    target_schema text,
    target_table text NOT NULL,
    write_mode text NOT NULL,
    key_columns jsonb,
    justification text,
    validation_status text,
    validation_report jsonb,
    status text DEFAULT 'pending'::text NOT NULL,
    reviewed_by uuid,
    reviewed_at timestamp with time zone,
    review_note text,
    executed_at timestamp with time zone,
    result jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    target_id uuid,
    contract_version integer,
    origin text DEFAULT 'file'::text NOT NULL,
    change_summary jsonb,
    CONSTRAINT upload_requests_origin_check CHECK ((origin = ANY (ARRAY['file'::text, 'studio'::text]))),
    CONSTRAINT upload_requests_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'completed'::text, 'failed'::text]))),
    CONSTRAINT upload_requests_target_type_check CHECK ((target_type = ANY (ARRAY['postgres'::text, 'bigquery'::text, 'oracle'::text]))),
    CONSTRAINT upload_requests_upsert_key_check CHECK (((write_mode <> 'upsert'::text) OR (jsonb_array_length(COALESCE(key_columns, '[]'::jsonb)) > 0))),
    CONSTRAINT upload_requests_validation_status_check CHECK ((validation_status = ANY (ARRAY['passed'::text, 'failed'::text]))),
    CONSTRAINT upload_requests_write_mode_check CHECK ((write_mode = ANY (ARRAY['append'::text, 'upsert'::text, 'update'::text])))
);


--
-- Name: upload_targets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.upload_targets (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    target_type text NOT NULL,
    database_name text NOT NULL,
    schema_name text,
    table_name text NOT NULL,
    display_name text NOT NULL,
    description text,
    write_modes text[] DEFAULT ARRAY['append'::text] NOT NULL,
    key_columns jsonb DEFAULT '[]'::jsonb NOT NULL,
    contract jsonb DEFAULT '{"columns": []}'::jsonb NOT NULL,
    contract_version integer DEFAULT 1 NOT NULL,
    schema_snapshot jsonb,
    is_active boolean DEFAULT true NOT NULL,
    created_by uuid,
    updated_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    onboarding_status text DEFAULT 'approved'::text NOT NULL,
    request_reason text,
    reviewed_by uuid,
    reviewed_at timestamp with time zone,
    review_note text,
    CONSTRAINT upload_targets_check CHECK ((('upsert'::text <> ALL (write_modes)) OR (jsonb_array_length(key_columns) > 0))),
    CONSTRAINT upload_targets_contract_version_check CHECK ((contract_version >= 1)),
    CONSTRAINT upload_targets_database_name_check CHECK (((database_name ~ '^[A-Za-z_][A-Za-z0-9_]*$'::text) AND (length(database_name) <= 1024))),
    CONSTRAINT upload_targets_description_check CHECK ((length(description) <= 2000)),
    CONSTRAINT upload_targets_display_name_check CHECK (((length(btrim(display_name)) >= 1) AND (length(btrim(display_name)) <= 200))),
    CONSTRAINT upload_targets_onboarding_status_check CHECK ((onboarding_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text]))),
    CONSTRAINT upload_targets_request_reason_check CHECK ((length(request_reason) <= 2000)),
    CONSTRAINT upload_targets_review_note_check CHECK ((length(review_note) <= 2000)),
    CONSTRAINT upload_targets_schema_name_check CHECK ((schema_name ~ '^[A-Za-z_][A-Za-z0-9_]{0,62}$'::text)),
    CONSTRAINT upload_targets_table_name_check CHECK (((table_name ~ '^[A-Za-z_][A-Za-z0-9_]*$'::text) AND (length(table_name) <= 1024))),
    CONSTRAINT upload_targets_target_type_check CHECK ((target_type = ANY (ARRAY['bigquery'::text, 'postgres'::text, 'oracle'::text]))),
    CONSTRAINT upload_targets_write_modes_check CHECK (((cardinality(write_modes) > 0) AND (write_modes <@ ARRAY['append'::text, 'upsert'::text])))
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email text NOT NULL,
    username text NOT NULL,
    first_name text,
    last_name text,
    password_hash text NOT NULL,
    password_changed_at timestamp with time zone DEFAULT now() NOT NULL,
    role text DEFAULT 'user'::text NOT NULL,
    status text DEFAULT 'pending_approval'::text NOT NULL,
    reviewed_by uuid,
    reviewed_at timestamp with time zone,
    last_login_at timestamp with time zone,
    failed_login_count integer DEFAULT 0 NOT NULL,
    locked_until timestamp with time zone,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT users_email_check CHECK (((email = lower(email)) AND (email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$'::text))),
    CONSTRAINT users_failed_login_count_check CHECK ((failed_login_count >= 0)),
    CONSTRAINT users_first_name_check CHECK ((length(first_name) <= 100)),
    CONSTRAINT users_last_name_check CHECK ((length(last_name) <= 100)),
    CONSTRAINT users_role_check CHECK ((role = ANY (ARRAY['user'::text, 'admin'::text]))),
    CONSTRAINT users_status_check CHECK ((status = ANY (ARRAY['pending_approval'::text, 'active'::text, 'rejected'::text, 'suspended'::text, 'deactivated'::text]))),
    CONSTRAINT users_username_check CHECK ((username ~ '^[a-z0-9][a-z0-9_.-]{1,49}$'::text))
);


--
-- Name: workspace_file_versions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workspace_file_versions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    file_id uuid NOT NULL,
    version integer NOT NULL,
    gcs_path text NOT NULL,
    row_count integer,
    size_bytes bigint,
    note text,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT workspace_file_versions_version_check CHECK ((version >= 1))
);


--
-- Name: workspace_files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workspace_files (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    folder_id uuid,
    original_name text NOT NULL,
    format text NOT NULL,
    current_version integer DEFAULT 1 NOT NULL,
    current_gcs_path text NOT NULL,
    row_count integer,
    column_meta jsonb,
    size_bytes bigint,
    is_permanent boolean DEFAULT false NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT workspace_files_current_version_check CHECK ((current_version >= 1)),
    CONSTRAINT workspace_files_format_check CHECK ((format = ANY (ARRAY['csv'::text, 'xlsx'::text, 'json'::text]))),
    CONSTRAINT workspace_files_original_name_check CHECK (((length(btrim(original_name)) >= 1) AND (length(btrim(original_name)) <= 512))),
    CONSTRAINT workspace_files_status_check CHECK ((status = ANY (ARRAY['active'::text, 'archived'::text])))
);


--
-- Name: workspace_folders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workspace_folders (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    parent_id uuid,
    name text NOT NULL,
    path text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT workspace_folders_name_check CHECK ((((length(btrim(name)) >= 1) AND (length(btrim(name)) <= 255)) AND (POSITION(('/'::text) IN (name)) = 0)))
);


--
-- Name: bq_access_requests bq_access_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bq_access_requests
    ADD CONSTRAINT bq_access_requests_pkey PRIMARY KEY (id);


--
-- Name: bq_datasets_cache bq_datasets_cache_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bq_datasets_cache
    ADD CONSTRAINT bq_datasets_cache_pkey PRIMARY KEY (id);


--
-- Name: bq_tables_cache bq_tables_cache_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bq_tables_cache
    ADD CONSTRAINT bq_tables_cache_pkey PRIMARY KEY (dataset_id, id);


--
-- Name: db_access_grants db_access_grants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.db_access_grants
    ADD CONSTRAINT db_access_grants_pkey PRIMARY KEY (id);


--
-- Name: db_access_requests db_access_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.db_access_requests
    ADD CONSTRAINT db_access_requests_pkey PRIMARY KEY (id);


--
-- Name: password_reset_requests password_reset_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_requests
    ADD CONSTRAINT password_reset_requests_pkey PRIMARY KEY (id);


--
-- Name: pg_databases pg_databases_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pg_databases
    ADD CONSTRAINT pg_databases_name_key UNIQUE (name);


--
-- Name: pg_databases pg_databases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pg_databases
    ADD CONSTRAINT pg_databases_pkey PRIMARY KEY (id);


--
-- Name: pg_tables_catalog pg_tables_catalog_database_id_table_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pg_tables_catalog
    ADD CONSTRAINT pg_tables_catalog_database_id_table_name_key UNIQUE (database_id, table_name);


--
-- Name: pg_tables_catalog pg_tables_catalog_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pg_tables_catalog
    ADD CONSTRAINT pg_tables_catalog_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: upload_requests upload_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.upload_requests
    ADD CONSTRAINT upload_requests_pkey PRIMARY KEY (id);


--
-- Name: upload_targets upload_targets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.upload_targets
    ADD CONSTRAINT upload_targets_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: workspace_file_versions workspace_file_versions_file_id_version_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_file_versions
    ADD CONSTRAINT workspace_file_versions_file_id_version_key UNIQUE (file_id, version);


--
-- Name: workspace_file_versions workspace_file_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_file_versions
    ADD CONSTRAINT workspace_file_versions_pkey PRIMARY KEY (id);


--
-- Name: workspace_files workspace_files_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_files
    ADD CONSTRAINT workspace_files_pkey PRIMARY KEY (id);


--
-- Name: workspace_folders workspace_folders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_folders
    ADD CONSTRAINT workspace_folders_pkey PRIMARY KEY (id);


--
-- Name: workspace_folders workspace_folders_user_id_path_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_folders
    ADD CONSTRAINT workspace_folders_user_id_path_key UNIQUE (user_id, path);


--
-- Name: bq_access_requests_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bq_access_requests_status_idx ON public.bq_access_requests USING btree (status);


--
-- Name: bq_access_requests_user_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bq_access_requests_user_idx ON public.bq_access_requests USING btree (user_id);


--
-- Name: db_access_grants_active_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX db_access_grants_active_idx ON public.db_access_grants USING btree (user_id) WHERE (revoked_at IS NULL);


--
-- Name: db_access_requests_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX db_access_requests_status_idx ON public.db_access_requests USING btree (status);


--
-- Name: db_access_requests_user_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX db_access_requests_user_idx ON public.db_access_requests USING btree (user_id, status);


--
-- Name: password_reset_requests_one_pending_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX password_reset_requests_one_pending_idx ON public.password_reset_requests USING btree (user_id) WHERE (status = 'pending'::text);


--
-- Name: pg_tables_catalog_database_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX pg_tables_catalog_database_idx ON public.pg_tables_catalog USING btree (database_id);


--
-- Name: upload_requests_file_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX upload_requests_file_idx ON public.upload_requests USING btree (file_id);


--
-- Name: upload_requests_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX upload_requests_status_idx ON public.upload_requests USING btree (status, created_at);


--
-- Name: upload_requests_target_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX upload_requests_target_idx ON public.upload_requests USING btree (target_id);


--
-- Name: upload_requests_user_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX upload_requests_user_idx ON public.upload_requests USING btree (user_id, created_at DESC);


--
-- Name: upload_targets_active_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX upload_targets_active_idx ON public.upload_targets USING btree (target_type, database_name) WHERE is_active;


--
-- Name: upload_targets_pending_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX upload_targets_pending_idx ON public.upload_targets USING btree (created_at) WHERE (onboarding_status = 'pending'::text);


--
-- Name: upload_targets_table_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX upload_targets_table_key ON public.upload_targets USING btree (target_type, database_name, COALESCE(schema_name, ''::text), table_name) WHERE (onboarding_status <> 'rejected'::text);


--
-- Name: users_email_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email);


--
-- Name: users_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_status_idx ON public.users USING btree (status, created_at) WHERE (deleted_at IS NULL);


--
-- Name: users_username_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX users_username_key ON public.users USING btree (username);


--
-- Name: workspace_files_folder_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workspace_files_folder_idx ON public.workspace_files USING btree (folder_id);


--
-- Name: workspace_files_user_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workspace_files_user_idx ON public.workspace_files USING btree (user_id, updated_at DESC) WHERE (status = 'active'::text);


--
-- Name: workspace_folders_parent_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX workspace_folders_parent_idx ON public.workspace_folders USING btree (parent_id);


--
-- Name: upload_targets upload_targets_set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER upload_targets_set_updated_at BEFORE UPDATE ON public.upload_targets FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: users users_set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER users_set_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: workspace_files workspace_files_set_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER workspace_files_set_updated_at BEFORE UPDATE ON public.workspace_files FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: bq_access_requests bq_access_requests_reviewed_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bq_access_requests
    ADD CONSTRAINT bq_access_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id);


--
-- Name: bq_access_requests bq_access_requests_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bq_access_requests
    ADD CONSTRAINT bq_access_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: db_access_grants db_access_grants_database_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.db_access_grants
    ADD CONSTRAINT db_access_grants_database_id_fkey FOREIGN KEY (database_id) REFERENCES public.pg_databases(id);


--
-- Name: db_access_grants db_access_grants_granted_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.db_access_grants
    ADD CONSTRAINT db_access_grants_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES public.users(id);


--
-- Name: db_access_grants db_access_grants_revoked_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.db_access_grants
    ADD CONSTRAINT db_access_grants_revoked_by_fkey FOREIGN KEY (revoked_by) REFERENCES public.users(id);


--
-- Name: db_access_grants db_access_grants_source_request_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.db_access_grants
    ADD CONSTRAINT db_access_grants_source_request_id_fkey FOREIGN KEY (source_request_id) REFERENCES public.db_access_requests(id);


--
-- Name: db_access_grants db_access_grants_table_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.db_access_grants
    ADD CONSTRAINT db_access_grants_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.pg_tables_catalog(id);


--
-- Name: db_access_grants db_access_grants_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.db_access_grants
    ADD CONSTRAINT db_access_grants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: db_access_requests db_access_requests_database_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.db_access_requests
    ADD CONSTRAINT db_access_requests_database_id_fkey FOREIGN KEY (database_id) REFERENCES public.pg_databases(id);


--
-- Name: db_access_requests db_access_requests_reviewed_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.db_access_requests
    ADD CONSTRAINT db_access_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id);


--
-- Name: db_access_requests db_access_requests_table_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.db_access_requests
    ADD CONSTRAINT db_access_requests_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.pg_tables_catalog(id);


--
-- Name: db_access_requests db_access_requests_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.db_access_requests
    ADD CONSTRAINT db_access_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: password_reset_requests password_reset_requests_resolved_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_requests
    ADD CONSTRAINT password_reset_requests_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: password_reset_requests password_reset_requests_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_requests
    ADD CONSTRAINT password_reset_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: pg_tables_catalog pg_tables_catalog_database_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pg_tables_catalog
    ADD CONSTRAINT pg_tables_catalog_database_id_fkey FOREIGN KEY (database_id) REFERENCES public.pg_databases(id) ON DELETE CASCADE;


--
-- Name: upload_requests upload_requests_file_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.upload_requests
    ADD CONSTRAINT upload_requests_file_id_fkey FOREIGN KEY (file_id) REFERENCES public.workspace_files(id) ON DELETE CASCADE;


--
-- Name: upload_requests upload_requests_reviewed_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.upload_requests
    ADD CONSTRAINT upload_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id);


--
-- Name: upload_requests upload_requests_target_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.upload_requests
    ADD CONSTRAINT upload_requests_target_id_fkey FOREIGN KEY (target_id) REFERENCES public.upload_targets(id) ON DELETE SET NULL;


--
-- Name: upload_requests upload_requests_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.upload_requests
    ADD CONSTRAINT upload_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: upload_targets upload_targets_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.upload_targets
    ADD CONSTRAINT upload_targets_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: upload_targets upload_targets_reviewed_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.upload_targets
    ADD CONSTRAINT upload_targets_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: upload_targets upload_targets_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.upload_targets
    ADD CONSTRAINT upload_targets_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: users users_reviewed_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: workspace_file_versions workspace_file_versions_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_file_versions
    ADD CONSTRAINT workspace_file_versions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: workspace_file_versions workspace_file_versions_file_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_file_versions
    ADD CONSTRAINT workspace_file_versions_file_id_fkey FOREIGN KEY (file_id) REFERENCES public.workspace_files(id) ON DELETE CASCADE;


--
-- Name: workspace_files workspace_files_folder_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_files
    ADD CONSTRAINT workspace_files_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES public.workspace_folders(id) ON DELETE SET NULL;


--
-- Name: workspace_files workspace_files_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_files
    ADD CONSTRAINT workspace_files_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: workspace_folders workspace_folders_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_folders
    ADD CONSTRAINT workspace_folders_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.workspace_folders(id) ON DELETE CASCADE;


--
-- Name: workspace_folders workspace_folders_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_folders
    ADD CONSTRAINT workspace_folders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


